// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_yDYg_UPMkZaMO9YBE2HhxXRcU6uvR0',
    appId: '1:708740677078:web:18a336e3f4db0ddb033877',
    messagingSenderId: '708740677078',
    projectId: 'boatbooking-a2b5e',
    authDomain: 'boatbooking-a2b5e.firebaseapp.com',
    storageBucket: 'boatbooking-a2b5e.appspot.com',
    measurementId: 'G-K761YRV6G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPjt55NOPIqjXDLX863ih8wDAoJQcK90',
    appId: '1:708740677078:android:df6bac9b0fb5ca69033877',
    messagingSenderId: '708740677078',
    projectId: 'boatbooking-a2b5e',
    storageBucket: 'boatbooking-a2b5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLwBPgok5BhbkZGPhyFF-u2xLJyzOtY8',
    appId: '1:708740677078:ios:41f441160feff852033877',
    messagingSenderId: '708740677078',
    projectId: 'boatbooking-a2b5e',
    storageBucket: 'boatbooking-a2b5e.appspot.com',
    androidClientId: '708740677078-od0tn5o9r481hgiqrs5crbkt73dn7pau.apps.googleusercontent.com',
    iosClientId: '708740677078-87p4bd06cr3pbhh0mqmi3n0n9unmrv49.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBoat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLwBPgok5BhbkZGPhyFF-u2xLJyzOtY8',
    appId: '1:708740677078:ios:5aacd010f8a1d599033877',
    messagingSenderId: '708740677078',
    projectId: 'boatbooking-a2b5e',
    storageBucket: 'boatbooking-a2b5e.appspot.com',
    androidClientId: '708740677078-od0tn5o9r481hgiqrs5crbkt73dn7pau.apps.googleusercontent.com',
    iosClientId: '708740677078-p126eb69m5ol5mb95s89p3fe34ljdqp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBoat.RunnerTests',
  );
}
