name: .NET Core Desktop
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted, self-hosted]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/setup-dotnet@v3.1.0
        with:
          dotnet-version: 7
      - uses: actions/checkout@v3.1.0
      - run: |
          NET STOP WAS /Y 
          dotnet publish boat-booking\boat-booking\Booking App WebApi\BookingAppWebApi.sln -c Release -o ./publishCodeBookingApp
          powershell -Command "Start-Sleep -s 10"
          powershell -Command "Copy-Item ./publishCodeBookingApp/* D:BoatBooking -Recurse -Force"
          NET START W3SVC
